import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    dashboard: 'Dashboard',
    timeline: 'Timeline',
    analytics: 'Analytics',
    settings: 'Settings',
    domains: 'Domains',
    logout: 'Logout',
    trustScore: 'Identity Trust Score',
    aiInsights: 'AI Strategic Intelligence',
    syncProtocols: 'Sync Protocols',
    processDomains: 'Institutional Domains',
    gotOffer: 'I got a new offer',
    needHealth: 'I need Health Insurance',
    initKYC: 'Initialize KYC Sync',
    mapBank: 'Map Bank Streams',
    continuityHeader: 'Your Continuity.',
    continuitySub: 'A living architecture of your digital existence, cross-referenced against institutional domains.',
    syncHealth: 'Sync Health Domain',
    syncIdentity: 'Initialize Identity Sync',
    mapFinance: 'Map Financial Destiny',
    voiceActive: 'Voice Protocol Active...',
    voiceAsk: 'Speak your command (e.g., "Go to Analytics")',
    stageIntelligence: 'Stage Intelligence',
    verifiedDocs: 'Verified Domain Documents',
    networkStatus: 'Network Status',
    strategicInsights: 'Strategic Insights',
    identityActive: 'Identity Active',
    syncNewTrajectory: 'Sync New Trajectory',
    syncHealthDomain: 'Sync Health Domain',
    initIdentitySync: 'Initialize Identity Sync',
    mapFinancialDestiny: 'Map Financial Destiny',
    verifiedAge: 'Verified Age',
    coverageBreadth: 'Coverage Breadth',
    detectedDocument: 'Detected Document',
    activeStreams: 'Active Streams',
    kycDesc: 'Institutional identity anchoring for all financial domains.',
    insuranceDesc: 'Biological risk mitigation tailored to your physical trajectory.',
    loanDesc: 'Academic capital bridge for future-role actualization.',
    identitySync: 'Identity Sync',
    biometricMatch: 'Biometric Match',
    hashAnchoring: 'Hash Anchoring',
    healthSync: 'Health Sync',
    planSelection: 'Plan Selection',
    quantumUnderwriting: 'Quantum Underwriting',
    degreeMatch: 'Degree Match',
    eligibilityCheck: 'Eligibility Check',
    creditStreamLink: 'Credit Stream Link',
    initializeProcess: 'Initialize Process',
    processSynchronized: 'Process Synchronized',
    continuityAutoFill: 'Continuity Auto-Fill',
    mappingProfile: 'AI Agent is mapping your profile...',
    fullName: 'Full Name',
    residencyMap: 'Residency Map',
    institutionalContinuity: 'Institutional Continuity Detected',
    syncSubmitProcess: 'Sync & Submit Process',
    kycTitle: 'KYC Verification',
    insuranceTitle: 'Health Insurance',
    loanTitle: 'Education Loan',
    intelligenceHeader: 'Intelligence.',
    intelligenceSub: 'Deep-layer verification metrics and growth trajectory analysis derived from your institutional continuity streams.',
    configHeader: 'Configuration.',
    configSub: 'Manage your connected institutional streams and fine-tune your sovereign privacy architecture.',
    verificationHistory: 'Verification History',
    growth6Month: '6-Month Continuous Growth',
    syncProtocol: 'Sync Protocol',
    forceProtocolSync: 'Force Protocol Sync',
    protocolSyncDesc: 'Data streams are synchronized on a 24-hour cryptographic cycle. Manual override requires re-authentication of your biological keys.',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    timeline: 'समयरेखा',
    analytics: 'विश्लेषिकी',
    settings: 'सेटअप',
    domains: 'डोमेन',
    logout: 'लॉगआउट',
    trustScore: 'पहचान ट्रस्ट स्कोर',
    aiInsights: 'एआई रणनीतिक बुद्धिमत्ता',
    syncProtocols: 'सिंक प्रोटोकॉल',
    processDomains: 'संस्थागत डोमेन',
    gotOffer: 'मुझे नया प्रस्ताव मिला',
    needHealth: 'मुझे स्वास्थ्य बीमा चाहिए',
    initKYC: 'केवाईसी सिंक शुरू करें',
    mapBank: 'बैंक स्ट्रीम मैप करें',
    continuityHeader: 'आपकी निरंतरता।',
    continuitySub: 'आपके डिजिटल अस्तित्व की एक जीवित वास्तुकला, संस्थागत डोमेन के साथ क्रॉस-रेफरेंस।',
    syncHealth: 'स्वास्थ्य डोमेन सिंक करें',
    syncIdentity: 'पहचान सिंक शुरू करें',
    mapFinance: 'वित्तीय भविष्य मैप करें',
    voiceActive: 'वॉयस प्रोटोकॉल सक्रिय...',
    voiceAsk: 'अपना कमांड बोलें (जैसे, "एनालिटिक्स पर जाएं")',
    stageIntelligence: 'स्टेज इंटेलिजेंस',
    verifiedDocs: 'सत्यापित डोमेन दस्तावेज़',
    networkStatus: 'नेटवर्क स्थिति',
    strategicInsights: 'रणनीतिक अंतर्दृष्टि',
    identityActive: 'पहचान सक्रिय',
    syncNewTrajectory: 'नया प्रक्षेपवक्र सिंक करें',
    syncHealthDomain: 'स्वास्थ्य डोमेन सिंक करें',
    initIdentitySync: 'पहचान सिंक शुरू करें',
    mapFinancialDestiny: 'वित्तीय भविष्य मैप करें',
    verifiedAge: 'सत्यापित आयु',
    coverageBreadth: 'कवरेज विस्तार',
    detectedDocument: 'पहचाना गया दस्तावेज़',
    activeStreams: 'सक्रिय स्ट्रीम',
    kycDesc: 'सभी वित्तीय डोमेन के लिए संस्थागत पहचान निर्धारण।',
    insuranceDesc: 'आपके शारीरिक प्रक्षेपवक्र के अनुरूप जैविक जोखिम शमन।',
    loanDesc: 'भविष्य की भूमिका को साकार करने के लिए शैक्षणिक पूंजी सेतु।',
    identitySync: 'पहचान सिंक',
    biometricMatch: 'बायोमेट्रिक मिलान',
    hashAnchoring: 'हैश एंकरिंग',
    healthSync: 'स्वास्थ्य सिंक',
    planSelection: 'योजना चयन',
    quantumUnderwriting: 'क्वांटम अंडरराइटिंग',
    degreeMatch: 'डिग्री मिलान',
    eligibilityCheck: 'पात्रता जांच',
    creditStreamLink: 'क्रेडिट स्ट्रीम लिंक',
    initializeProcess: 'प्रक्रिया शुरू करें',
    processSynchronized: 'प्रक्रिया सिंक्रनाइज़',
    continuityAutoFill: 'निरंतरता ऑटो-फिल',
    mappingProfile: 'एआई एजेंट आपकी प्रोफ़ाइल मैप कर रहा है...',
    fullName: 'पूरा नाम',
    residencyMap: 'निवास नक्शा',
    institutionalContinuity: 'संस्थागत निरंतरता का पता चला',
    syncSubmitProcess: 'सिंक और प्रक्रिया सबमिट करें',
    kycTitle: 'केवाईसी सत्यापन',
    insuranceTitle: 'स्वास्थ्य बीमा',
    loanTitle: 'शिक्षा ऋण',
    intelligenceHeader: 'बुद्धिमत्ता।',
    intelligenceSub: 'आपके संस्थागत निरंतरता स्ट्रीम से प्राप्त गहरे स्तर के सत्यापन मेट्रिक्स और विकास प्रक्षेपवक्र विश्लेषण।',
    configHeader: 'कॉन्फ़िगरेशन।',
    configSub: 'अपने जुड़े हुए संस्थागत स्ट्रीम प्रबंधित करें और अपने संप्रभु गोपनीयता वास्तुकला को फाइन-ट्यून करें।',
    verificationHistory: 'सत्यापन इतिहास',
    growth6Month: '6-महीने का निरंतर विकास',
    syncProtocol: 'सिंक प्रोटोकॉल',
    forceProtocolSync: 'फोर्स प्रोटोकॉल सिंक',
    protocolSyncDesc: 'डेटा स्ट्रीम 24 घंटे के क्रिप्टोग्राफिक चक्र पर सिंक्रनाइज़ होते हैं। मैनुअल ओवरराइड के लिए आपकी जैविक कुंजियों के पुन: प्रमाणीकरण की आवश्यकता होती है।',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
